[[redirects]]
  from = "/proxy/*"
  to = "https://192.168.0.75:8080/:splat"
  status = 200
  force = true

  [[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''